version : '3.7'

services:
  order-center:
    container_name: order-center
    hostname: order-center
    restart: always
    image: tcr.xjzmy.io/zmydev/order-center:xjzmy-dev-v1.0.0.4
    labels:
      maintainers: "jiangt.tao"
    network_mode: "host"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:58081/actuator/health"]
      interval: 60s
      timeout: 10s
      retries: 3
    ports:
      - 58081:58081
    volumes:
      - /TRS/LOGS/order-center:/TRS/LOGS/order-center
      - /TRS/DATA/order-center:/TRS/DATA/order-center
