version : '3.7'
 
services:
  screen-data-access:
    container_name: screen-data-access
    hostname: screen-data-access
    restart: always
    image: tcr.xjzmy.io/zmytest/screen-data-access:$tag_name
    labels:
      maintainers: "liao.peng<liao.peng@trs.com.cn>"
    network_mode: "host"
    ports:
      - 9995:9995
      - 2000:2000
      - 2041:2041
      - 2042:2042
      - 2043:2043
      - 2044:2044
      - 2045:2045
      - 2046:2046
      - 2047:2047
      - 2008:2008
      - 2020:2020
      - 2022:2022
      - 2040:2040
    volumes:
      - /TRS/LOGS/screen-data-access:/TRS/LOGS/screen-data-access
      - /TRS/DATA/web/bigscreen:/TRS/DATA/web/bigscreen
